name: Josh Hornby
description: Talking about web development
meta_description: "Josh Hornby talks web development"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://joshhornby.co.uk'
google_analytics: 'UA-29844067-2'
disqus: true
disqus_shortname: 'joshhornbyblog'

# Details for the RSS feed generator
url:            'http://joshhornby.co.uk'
author:         'Josh Hornby'
authorTwitter:  'joshua_hornby'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
