# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Joshua Hornby"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /blog/:title

# Markdown
markdown:           redcarpet
redcarpet:
  extensions: ["strikethrough"]

# Navigation
#nav:
#  - name:           "About"
#    href:           "/about"

# Sass
sass:
  style:            :compressed

# GA
google_analytics: 'UA-29844067-2'

# Disqus
disqus: true
disqus_shortname: 'joshhornbyblog'

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
