title: Josh Hornby
author:
  name: Josh Hornby
  avatar: null
  email: hello@joshhornby.co.uk
  url: null
baseurl: ''
url: 'https://joshhornby.com'
permalink: '/:title'
markdown: kramdown
kramdown:
  input: GFM
  coderay_line_numbers: ''
sass:
  style: compressed
google_analytics: UA-29844067-2
locale: en_GB
logo: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚙️️</text></svg>"
social:
  name: Josh Hornby
  links:
    - 'https://twitter.com/joshua_hornby'
    - 'https://www.linkedin.com/in/joshua-hornby-3a01621b5/'
    - 'https://github.com/joshhornby'
twitter:
  username: joshua_hornby
  card: summary_large_image
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at
