name:               "Joshua Hornby"

author:
  name: "Josh Hornby"
  avatar:
  email: "hello@joshhornby.co.uk"
  url: #yoururl

baseurl:            ""
siteUrl:            "https://joshhornby.co.uk"
permalink:          /blog/:title

markdown:           kramdown
kramdown:
  input: GFM
  coderay_line_numbers: ''

google_analytics: 'UA-29844067-2'

defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
