name: Josh Hornby
author:
  name: Josh Hornby
  avatar: null
  email: hello@joshhornby.co.uk
  url: null
baseurl: ''
url: 'https://joshhornby.com'
permalink: '/blog/:title'
markdown: kramdown
kramdown:
  input: GFM
  coderay_line_numbers: ''
sass:
  style: compressed
google_analytics: UA-29844067-2
locale: en_GB
logo: 'https://joshhornby.com/assets/images/logo.png'
social:
  name: Josh Hornby
  links:
    - 'https://twitter.com/joshua_hornby'
    - 'https://www.linkedin.com/in/joshua-hornby-3a01621b5/'
    - 'https://github.com/joshhornby'
twitter:
  username: joshua_hornby
  card: summary
collections:
  newsletters:
    permalink: '/newsletters/:title'
    output: true
  books:
    permalink: '/books/:title'
    output: true
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
plugins:
  - jekyll-seo-tag
