name: Build and deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install Ruby to be able to build the site using Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      # Install Node as this is needed for PurgeCSS
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Install PurgeCSS (needs to be in your package.json)
      - run: npm install
      # Build site
      - name: Install dependencies & Build Site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      # Push the compiled _site-folder as branch into your GitHub repository
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site